version: '3.1'

services:

  database-app:
    container_name: database-app
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3309:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo